### PR TITLE
package.json updates when debugging

### PR DESCRIPTION
**Pull request by clue4**
package.json updates -- should all be safe!

### CODE REVIEW

**Review by jaron-cui — CHANGES_REQUESTED** [review]
Is there any particular reason why jest-expo was downgraded to 46.0.0 from 46.0.1?

**Comment by clue4** [comment]
> Is there any particular reason why jest-expo was downgraded to 46.0.0 from 46.0.1?

My assumption would be that jest-expo 46.0.0 is better suited for the other packages since I ran commands some expo commands that I believe checked for package compatibility and related things. I can't remember off the top of my head but iirc it was expo doctor (or update)? and some other ones

**Comment by clue4** [comment]
> > Is there any particular reason why jest-expo was downgraded to 46.0.0 from 46.0.1?
> 
> My assumption would be that jest-expo 46.0.0 is better suited for the other packages since I ran commands some expo commands that I believe checked for package compatibility and related things. I can't remember off the top of my head but iirc it was expo doctor (or update)? and some other ones

expo doctor --fix-dependencies was one of them

**Review by jaron-cui — APPROVED** [review]
Ok, looks fine otherwise.

**Pull request merged**
