### PR TITLE
Attendee list preliminary implementation 

### LINKED ISSUE #49: Show attendees list on event page (Milestone 1 part 2)
Follow the [designs](https://www.figma.com/file/ay7xX8FXxdR03bwBOYv6vX/ScoutTrek?node-id=154%3A156&t=Oo0d7Kvu4LCcbaU4-0) to create a list of attendees for each event.

- [ ] Attendees list shows below event info
- [ ] List is scrollable 
- [ ] Tabs for different RSVP categories
    - [ ] All (shows everyone in the troop)
    - [ ] Yes, No, Maybe, No Response
- [ ] After part 0 ticket, connect to backend to populate list

### PR DESCRIPTION
**Pull request by dylan-pham**
# Description

This is a preliminary frontend implementation of the attendee list. Still need to refine it by changing some colors.

## Figma Designs

Include a link to the Figma design here if neccesary.

## Screenshots/Video

Include screenshots of added features/bugfixes if neccesary.

### CODE REVIEW

**Comment by dylan-pham** [comment]
Screenshot 2023-04-05 at 8 03 33 PM

UI updated @dewikalis @grantallison

**Review by grantallison — CHANGES_REQUESTED** [review]
This looks good! Before we can approve it please increase the line spacing in between the names on the "Attendees" list. Also please remove the background color on the attendees bar where it lists "All, Yes, No, Maybe, etc" and make selected tabs green text with underline. Also make icons green, thanks!

**Comment by dylan-pham** [comment]
Screenshot 2023-04-09 at 4 17 12 PM

@grantallison I updated the UI

**Review by grantallison — APPROVED** [review]
Looks great!

**Pull request merged**
